version: '3.2'

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:13.0
    container_name: postgres
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"