app:
  depends_on:
    - kafka
    - postgres
  build: ..
  container_name: "employee-app"
  ports:
    - "8081:8081"
  environment:
    POSTGRES: "postgres"
    KAFKA: "kafka"
    KAFKA_LISTEN: "9092"