pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps{
                git branch: 'EmployeeBalanceLoad',
                    url: 'https://github.com/tharodon/EmployeeSOAP.git'
                }
        }
        stage('Build docker images') {
            steps{
                    sh 'docker build -t tharodon/employee-eureka-server:0.1 service/eureka-server/'
                    sh 'docker build -t tharodon/employee-api-gateway:0.1 service/api-gateway/'
                    sh 'docker build -t tharodon/employee:0.1 service/employee-service/'
            }
        }
        stage('Push docker image to DockerHub') {
            steps{
                withDockerRegistry(credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/') {
                    sh '''
                        docker push tharodon/employee:0.1
                    '''
                }
            }
        }
        stage('Deploy') {
                    steps {
                  sshagent(['ubuntu-key']) {
                    sh 'ssh -o StrictHostKeyChecking=no tharodon@192.168.47.128 bash pull_run_image.sh'
                  }
              }
                }
    }
}
