pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps{
                git branch: 'EmployeeBalanceLoad',
                    url: 'https://github.com/tharodon/EmployeeSOAP.git'
                }
        }
        stage('Build docker images') {
            steps{
                    sh 'docker build -t tharodon/employee-eureka-server:0.1 service/eureka-server/'
                    sh 'docker build -t tharodon/employee-api-gateway:0.1 service/api-gateway/'
                    sh 'docker build -t tharodon/employee:0.1 service/employee-service/'
            }
        }
        stage('Push docker image to DockerHub') {
            steps{
                withDockerRegistry(credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/') {
                    sh '''
                        docker push tharodon/employee-eureka-server:0.1
                        docker push tharodon/employee-api-gateway:0.1
                        docker push tharodon/employee:0.1
                    '''
                }
            }
        }
        stage('Deploy') {
                    steps {
                  sshagent(['ubuntu-key']) {
                    sh 'ssh -o StrictHostKeyChecking=no tharodon@192.168.47.128 bash run-services.sh'
                  }
              }
        }

        post {
            success {
              sh 'curl https://api.telegram.org/bot5562491817:AAF-keU0csfRVFpdpVU1_kxp8bFNX9fBMTE/sendMessage -d chat_id=-1001573982949 -d parse_mode=markdown -d text="Сборка завершена удачно❤️"'
              }
            failure{
                sh 'curl https://api.telegram.org/bot5562491817:AAF-keU0csfRVFpdpVU1_kxp8bFNX9fBMTE/sendMessage -d chat_id=-1001573982949 -d parse_mode=markdown -d text="Сборка завершена неудачно😕️"'
            }
            aborted{
                sh 'curl https://api.telegram.org/bot5562491817:AAF-keU0csfRVFpdpVU1_kxp8bFNX9fBMTE/sendMessage -d chat_id=-1001573982949 -d parse_mode=markdown -d text="Сборка прервана❤️"'
            }
        }

    }
}
